Improve and migrate clear/purge command
LorittaBot/Loritta pull request #2280
Opened 2020-12-01 13:27 UTC by SrGaabriel

This pull request closes #2278

* Loritta: x
* Locales: y

2020-12-02 15:59 UTC, MrPowerGamerBR requested changes

2020-12-02 15:59 UTC, MrPowerGamerBR commented on loritta-discord/src/main/java/net/perfectdreams/loritta/commands/vanilla/administration/ClearCommand.kt
> +            if (count == null || count !in 2..500)
I think it can be higher than 500 (maybe 1000?)

2020-12-02 15:59 UTC, MrPowerGamerBR commented on loritta-discord/src/main/java/net/perfectdreams/loritta/commands/vanilla/administration/ClearCommand.kt
> +        channel.sendMessage("").queue()
Why tho

2020-12-02 15:59 UTC, MrPowerGamerBR commented on loritta-discord/src/main/java/net/perfectdreams/loritta/commands/vanilla/administration/ClearCommand.kt
> +                .expireAfterAccess(4, TimeUnit.SECONDS)
Would be nice to increase the purge task from 4 seconds to *maximum message purge / 100* (let's suppose that 1 request will be executed every second, so if the max is 500 = 5 seconds)

2020-12-02 15:59 UTC, MrPowerGamerBR commented on loritta-discord/src/main/java/net/perfectdreams/loritta/commands/vanilla/administration/ClearCommand.kt
> +        discordMessage.textChannel.purgeMessages(messages) // Purging the messages
Something to keep in mind: If this commands ends up having some issues, let's copy JDA's function and then add some delays between every purge. (to avoid ratelimiting)

https://github.com/DV8FromTheWorld/JDA/blob/3a9fcd0ecc88f988ac81eb2c18527283a83f12d1/src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java#L217

2020-12-02 16:06 UTC, MrPowerGamerBR requested changes

2020-12-02 16:06 UTC, MrPowerGamerBR commented on loritta-discord/src/main/java/net/perfectdreams/loritta/utils/ReplyUtils.kt
> +suspend fun CommandContext.styledReply(builder: ReplyBuilder.() -> Unit) =
Would be nice if the same was `sendStyledReply`, because `styledReply` feels like something that builds the reply, not send it.

2020-12-02 17:47 UTC, MrPowerGamerBR requested changes

2020-12-02 17:47 UTC, MrPowerGamerBR commented on loritta-discord/src/main/java/net/perfectdreams/loritta/commands/vanilla/administration/ClearCommand.kt
> +        discordMessage.textChannel.purgeMessages(messages) // Purging the messages
After finishing the purge, the guild ID should be removed from the `unavailableGuilds` list

2020-12-02 17:53 UTC, MrPowerGamerBR commented
Another thing: I think that the text filter is a bit "unintuitive"

It would be better if the filter was something like Discord's search:

`+clear 5 text here from:@SrGaabriel`

2020-12-03 02:03 UTC, SrGaabriel commented on loritta-discord/src/main/java/net/perfectdreams/loritta/commands/vanilla/administration/ClearCommand.kt
> +        unavailableGuilds.remove(guild.idLong)
@MrPowerGamerBR The changes were made but I don't understand why we should remove the guild instantly instead of waiting the 5 seconds we defined at the `unavailableGuilds` list.

2020-12-03 02:04 UTC, SrGaabriel commented
New pull request to the locales repository implementing some changes: https://github.com/LorittaBot/LorittaLocales/pull/119/

2020-12-03 12:39 UTC, MrPowerGamerBR requested changes

2020-12-03 12:39 UTC, MrPowerGamerBR commented on loritta-discord/src/main/java/net/perfectdreams/loritta/commands/vanilla/administration/ClearCommand.kt
> +        unavailableGuilds.remove(guild.idLong)
Because the cooldown is used as "in the worst case, this is how much time will be used to purge the messages" (and the cooldown time should be increased too", also because Caffeine will only remove the ID from the cache after someone accesses the cache map again. (because Caffeine only purges stuff from cache on map access/write).

Also because someone could run "+clear 1000" and the task would be finished pretty fast (remember that the time right now is the *worst* possible scenario: one request per second (I would increase it to one request every 5 seconds just to be safe) and then the user would run the command again and Loritta would say "nope there is still a task running"

2020-12-03 12:39 UTC, MrPowerGamerBR commented on loritta-discord/src/main/java/net/perfectdreams/loritta/commands/vanilla/administration/ClearCommand.kt
> +                && (it.isPinned.not()) // The message can't be pinned
Why not "`!it.isPinned`?

2020-12-03 12:39 UTC, MrPowerGamerBR commented on loritta-discord/src/main/java/net/perfectdreams/loritta/commands/vanilla/administration/ClearCommand.kt
> +        val options = args.drop(1).joinToString("").trim().split("from")
For this: I would prefer that the `from` string was in the locales because Discord's search also changes depending on your language.

2020-12-03 12:43 UTC, SrGaabriel commented on loritta-discord/src/main/java/net/perfectdreams/loritta/commands/vanilla/administration/ClearCommand.kt
> +                && (it.isPinned.not()) // The message can't be pinned
Because it's prettier

2020-12-03 14:51 UTC, merged