Send DM when divorce
LorittaBot/Loritta pull request #2292
Opened 2020-12-08 02:27 UTC by iiAmFilippi

https://github.com/LorittaBot/Loritta/issues/2289

2020-12-08 10:53 UTC, SrGaabriel commented
This will throw exceptions if the user has its DM closed or blocked Loritta.

2020-12-08 11:04 UTC, SrGaabriel commented
And you should fix the code formatting.

2020-12-08 11:11 UTC, iiAmFilippi commented
> 
> 
> And you should fix the code formatting.

as well?

2020-12-08 12:46 UTC, MrPowerGamerBR commented
I think that it would be better if the message was prettier in a embed:

Something like this:
![image](https://user-images.githubusercontent.com/9496359/101485668-39783e00-393a-11eb-85de-16d751ffa9f3.png)

2020-12-08 14:24 UTC, iiAmFilippi commented
already made the changes

2020-12-08 14:59 UTC, SrGaabriel requested changes

2020-12-08 14:59 UTC, SrGaabriel commented on loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/social/DivorceCommand.kt
> +						val userDM = user?.openPrivateChannel()?.await()
Try using this and then remove the null safety characters:

```suggestion
						val userPrivateChannel = user?.openPrivateChannel()?.await() ?: return
```

2020-12-08 14:59 UTC, SrGaabriel commented on loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/social/DivorceCommand.kt
>  					)
I think you should fix the code formatting, like on this line.

2020-12-08 14:59 UTC, SrGaabriel commented on loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/social/DivorceCommand.kt
> +								.setThumbnail("https://cdn.discordapp.com/emojis/556524143281963008.png?size=2048")
Migrate this URI to the companion object

2020-12-08 14:59 UTC, SrGaabriel commented on loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/social/DivorceCommand.kt
> +		val user = lorittaShards.getUserById(userId)
You should get the marriage data using the `ProfileUtils.kt` class.

2020-12-11 19:24 UTC, MrPowerGamerBR requested changes

2020-12-11 19:24 UTC, MrPowerGamerBR commented on loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/social/DivorceCommand.kt
> +								.setThumbnail("https://cdn.discordapp.com/emojis/556524143281963008.png?size=2048")
^ That's not really necessary but would be nice to change it

2020-12-11 19:24 UTC, MrPowerGamerBR commented
pls fix the stuff that Gabriel suggested

2020-12-14 00:53 UTC, iiAmFilippi commented
Done.

2020-12-15 14:31 UTC, MrPowerGamerBR commented
looks good to me

2020-12-15 16:04 UTC, iiAmFilippi commented
:lori_ameno:

2020-12-15 16:07 UTC, merged