Adding a 'return' button for ReminderCommand.
LorittaBot/Loritta pull request #2315
Opened 2020-12-20 15:20 UTC by VitorBlog

Idk if it's working because my knowledge of the loritta api is very basic.

2020-12-20 15:49 UTC, SrGaabriel requested changes
This is why the build is failing.

2020-12-20 15:49 UTC, SrGaabriel commented on loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/utils/LembrarCommand.kt
> +				val message = context.sendMessage("locale["${LOCALE_PREFIX}.reminderRemoved"]")
```suggestion
				val message = context.sendMessage(locale["${LOCALE_PREFIX}.reminderRemoved"])
```

2020-12-21 15:38 UTC, MrPowerGamerBR commented
You could try selfhosting Loritta and see if it works or not

2021-02-25 14:49 UTC, VitorBlog commented
Tested
![loretta](https://user-images.githubusercontent.com/35616041/109170390-7d235c80-775f-11eb-8caa-64fa1e066ba2.gif)

2021-02-25 15:05 UTC, VitorBlog commented
Better GIF
![lorota](https://user-images.githubusercontent.com/35616041/109172527-a349fc00-7761-11eb-84da-a475cccfab2f.gif)

2021-02-25 15:11 UTC, VitorBlog commented
When testing, I noticed that the reminder doesn't translate because the 'remindme.yml' file only exists on default locale.

2021-02-27 15:36 UTC, MrPowerGamerBR commented
LGTM

![https://cdn.discordapp.com/emojis/706263175892566097.gif?v=1](https://cdn.discordapp.com/emojis/706263175892566097.gif?v=1)

2021-02-27 15:36 UTC, merged