Ranking page index rework and version update
LorittaBot/Loritta pull request #2359
Opened 2021-01-18 18:55 UTC by nekkan

This pull requests is intended to make the following updates:
* Update Kotlin and kotlinx.coroutines (1.4.10 -> 1.4.20, 1.4.1 -> 1.4.2);
* Update Gradle to use the latest performance improvements and bug fixes (6.4.2 -> 6.8);
* Make transactions 'page' variable a val instead of var using elvis operator;
* Rewrite the page retrieving in ranking commands:*
```kotlin
// old
var page = context.args.getOrNull(0)?.toLongOrNull()
    
if (page != null && !RankingGenerator.isValidRankingPage(page)) {
    context.reply(
        LorittaReply(
            locale["commands.invalidRankingPage"],
            Constants.ERROR
        )
    )
    return@executesDiscord
}

if (page != null)
    page -= 1

if (page == null)
    page = 0

// new
val pageIndex = when (val value = context.args.getOrNull(0)?.toLongOrNull()?.coerceAtLeast(0)) {
    0L, null -> 0L
    else -> {
        if (!RankingGenerator.isValidRankingPage(value)) {
            context.reply(LorittaReply(locale["commands.invalidRankingPage"], Constants.ERROR))
            return@executesDiscord
        }
        value - 1
    }
}
```

2021-01-18 21:47 UTC, MrPowerGamerBR requested changes
Also, it is better to keep everything as TABs instead of spaces

2021-01-18 21:47 UTC, MrPowerGamerBR commented on build.gradle.kts
> +val kotlinVersion = "1.4.20"
The latest Kotlin version is 1.4.21

2021-02-24 20:35 UTC, MrPowerGamerBR commented
I personally thing that, while the new code is shorter, it is way more unreadable compared to the old one.

2021-02-25 01:35 UTC, nekkan commented
> I personally thing that, while the new code is shorter, it is way more unreadable compared to the old one.

I don't think so, besides it is always good to maintain good practices

2021-02-28 09:18 UTC, closed without merging