Social Commands
LorittaBot/Loritta pull request #2467
Opened 2021-12-09 18:12 UTC by onlyfx

2021-12-09 18:14 UTC, onlyfx commented
This should be accepted after having sonhos transactions and member permissions v2 systems

2021-12-16 01:11 UTC, MrPowerGamerBR requested changes

2021-12-16 01:11 UTC, MrPowerGamerBR commented on pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/services/MarriagesService.kt
> +            val marriage = createMarriage(userProfile.id, partnerProfile.id)[Marriages.id]
Due to the way `pudding.transaction` works, this will create a nested transaction.

If the outer transaction fails (with "concurrent access"), the marriage will be created again, and having two marriages in the database is not a good thing

I still wonder if it is possible to fix this however, so for now what I recommend doing is creating a function that runs
```kotlin
            val insertStatement = Marriages.insert {
                it[Marriages.user1] = user1Id
                it[Marriages.user2] = user2Id
                it[Marriages.marriedSince] = System.currentTimeMillis()
            }

            insertStatement
```
not within a `transaction` block, similar to what I did with `getTicker(...)` in the `BovespaBrokerService`

2021-12-16 01:11 UTC, MrPowerGamerBR commented on pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/entities/PuddingUserProfile.kt
> +    suspend fun marriageDivorce() = pudding.transaction {
Keep transactions in the `Services` classes

2021-12-16 01:11 UTC, MrPowerGamerBR commented on pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/entities/PuddingProfileSettings.kt
> +    suspend fun setAboutMe(text: String) = pudding.transaction {
Keep transactions in the `Services` classes

2021-12-16 01:11 UTC, MrPowerGamerBR commented on pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/entities/PuddingGuildProfile.kt
> +    suspend fun addXp(amount: Long) = pudding.transaction {
Keep transactions in the `Services` classes

2021-12-16 01:11 UTC, MrPowerGamerBR commented on pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/entities/PuddingGuildProfile.kt
> +    suspend fun setXp(amount: Long) = pudding.transaction {
Keep transactions in the `Services` classes

2021-12-16 01:11 UTC, MrPowerGamerBR commented on pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/entities/PuddingGuildProfile.kt
> +    suspend fun removeXp(amount: Long) = pudding.transaction {
Keep transactions in the `Services` classes

2021-12-16 01:11 UTC, MrPowerGamerBR commented on discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/social/marriage/DivorceProposalButtonClickExecutor.kt
> +        authorProfile.marriageDivorce()
Both should be done in the same transaction

```kotlin
pudding.transaction {
    // Remove the marriage reference from both users
    // Delete the marriage object from the database
}
```

2021-12-16 01:11 UTC, MrPowerGamerBR commented on discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/social/declarations/EditXpCommand.kt
> +    override fun declaration() = command(listOf("editxp"), CommandCategory.SOCIAL, TodoFixThisData) {
Even though the description isn't visible on Discord yet, it is still nice to provide a description to the root command

2021-12-16 01:11 UTC, MrPowerGamerBR commented on discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/social/SetXpExecutor.kt
> +        if (amount < 0)
To be consistent with other checks in the codebase: `amount > 0`

2022-08-01 16:47 UTC, closed without merging